import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

export async function GET() {
  try {
    // For now, we mock the user ID since authentication is a later phase
    const mockUserId = "demo-user-id";
    
    // Attempt to fetch existing score
    let readiness = await db.readinessScore.findUnique({
      where: { userId: mockUserId }
    });
    
    if (!readiness) {
       // If no score exists (e.g. first time login), return a base evaluation 
       // In a real app, this would be generated by Gemini based on user onboarding data
       readiness = {
         id: "temp-id",
         userId: mockUserId,
         score: 45,
         locationScore: 50,
         familyScore: 60,
         suppliesScore: 30,
         lastCalculated: new Date()
       };
    }
    
    return NextResponse.json({ readiness }, { status: 200 });
  } catch (error) {
    console.error('Readiness API Error:', error);
    return NextResponse.json({ error: 'Failed to fetch readiness score' }, { status: 500 });
  }
}
